
# Appendix {#appendix}

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r load-packages, include=F}
library(tidyverse)
library(kableExtra)
```



```{r labor-per-area-tab, eval= T, echo=F, warning=F, message=F}
labor_man_hrs <- read_csv('data/lit-review-data/maintenance-man-hrs.csv') %>% 
  mutate(type= as_factor(type),
         type= fct_relevel(type, 'Game mound/bullpen', 'Home plate', 'Infield skin', 'Turf', 'Warning track')) %>% 
  arrange(type) %>% 
  select(type, name, time, people, time_min) %>% 
  rename(Task= name, `Field area`= type, `Prep time`=time, `Participants`=people,
         `Approx. duration (minutes)`= time_min) %>% 
  arrange(`Field area`) %>% 
  group_by(`Field area`)

labor_man_hrs %>% 
  kbl(align = "lllcc", caption = 'Field preparation tasks for a typical MLB game day.', longtable = TRUE, booktabs = TRUE) %>% 
  kable_styling(full_width = F, bootstrap_options = 'striped', latex_options = c('striped', "repeat_header") )

```



<!-- scatter for sand replacement vs 3D scanner methods for computing dry density 
 of ~21 mm plug   -->

```{r sand-backfill-vs-3D-scanner-for-volumetric-w-determination-table}
# read data frame  
sand_backfill_vs_scanner_vol_data <- readr::read_rds(fs::path(
  '../../cleatmarkmethod/ecmdata/derived-data/cleaned-rds-files/mini-plug-density-comp-cleaned-data.rds') )

# compute summary tibble 
sd_df <-  sand_backfill_vs_scanner_vol_data %>% 
  dplyr::group_by(cylinder_ID, vol_method) %>% 
  dplyr::summarise(dplyr::across(dry_density, 
                                 list(mean = mean, sd = sd), 
                                 .names="{.fn}"),
                   .groups = 'drop')

# generate kable
sd_df %>% 
  pivot_wider(names_from = vol_method,
              values_from = c(mean, sd)) %>% 
  kableExtra::kbl(x = .,
                  format = 'latex',
                  digits = c(0,2,2,3,3),
                  row.names = FALSE,
                  col.names = c('Cylinder ID',
                                rep(c('Sand replacement', '3D scanner'), 2)),
                  align = 'c',
                  caption = 'The 3D scanner produced much less variation in the computed dry density than the sand replacement method ',
                  escape = FALSE,
                  booktabs = TRUE,
                  centering = TRUE,
                  caption.short = 'Dry density for plugs using sand replacement vs. 3D scanner',
                  linesep = c("", "", "\\addlinespace")
                  
                  ) %>% 
  kableExtra::add_header_above(header = c(" " = 1, "$\\\\bar{x}$" = 2, "$\\\\sigma$"= 2), escape = FALSE) %>% 
  kableExtra::kable_styling(position = 'center')

# compute some values from the table for use in dynamic references 


# print the actual table 





```
