---
title: "Evan's PhD thesis proposal"
author: "Evan C Mascitti"
date: "``last compiled `r ecmfuns::ecm_timestamp()` ``"
site: bookdown::bookdown_site
documentclass: book
always_allow_html: true
keep_md: false
classoption: 
  - openany
linestretch: 1.2
links-as-notes: false
papersize: letter
# for final thesis submission to allow binding:
geometry: "left=1.5in, right=1.5in, top=1in, bottom=1in"  
# remember to specify whether thesis should be printed one or two sided as 
# this will affect the margins !!! 
# geometry: "left=1in, right=1in, top=1in, bottom=1in"  
bibliography: [packages.bib, library.bib]
csl: soil-science-society-of-america-journal.csl
biblio-title: "References"
link-citations: yes
description: "This is my first attempt at compiling a large dynamic document with the **bookdown** package in R."
mainfont: "Roboto"
mathfont: "Fira Math Regular"
toc: false
nocite: |
    @Monkul2007, @Cabalar2011, @Lade1998; @Ueda2011,
    @Thevanayagam1998, @Vallejo2000, @Cabalar2017, @Kim2018, @Cabalar2011,
    @Carrera2011, @Shipton2012, @Lade1997, @Zuo2015, @Kenney1991 
    # these are shown in a table but I don't want to list all of them out in the text
---


# Executive summary {.unnumbered #exeuctive-summary}

This document outlines the research progress I have made since beginning my PhD in 2019 and describes my plans for completing the project.
It comprises 4 main sections:

Section \@ref(purpose-and-objectives), [Purpose and objectives](#purpose-objectives)

:  High-level overview of project goals.



Section \@ref(problem-description), [Problem description](#problem-description)

:  Outlines the importance of the infield skin.



Section \@ref(lit-review), [Review of literature](#lit-review)

:  Summary of relevant prior scientific research. 
<!-- Includes 3 major sub-sections: (1) research on baseball/softball infields, (2) laboratory soil testing methods, and (3) the behavior of artificial soil mixtures. -->

Section \@ref(proposed-experiments), [Proposed experiments](#proposed-experiments)

:  Detailed outline of my research plan.
<!-- Planned course of laboratory research, organized as anticipated publication units. -->


I have also included a description of my workflow and data management practices (Section \@ref(workflow)). 
This section is written informally. 
Although it is un-related to the technical/soils aspects of my project, I included it because it comprises an important practical part of completing my degree.
Regardless of whether the reader finds this section enlightening, writing it has served as a useful "statement of beliefs" for me.

The proposal concludes with a [glossary](#definition-of-terms), an [Appendix](#appendix) housing some additional tables and equations, and my [references](#references).


<!-- I turned off the default TOC and I am inserting the  -->
<!-- contents and lists of figs and tables here manually with LaTeX. -->
<!-- It is a bit hacky but it works....using the bookmark package  -->
<!-- from CTAN to allow the contents to be bookmarked in the resulting -->
<!-- pdf file. Probably same thing would work for figs and tables -->
<!-- lists but need to take the time to learn what the arguments mean -->

\tableofcontents

\pdfbookmark[chapter]{\contentsname}{toc}

\listoffigures


\listoftables


<!-- ```{=latex} -->
<!-- \newpage  -->

<!-- \tableofcontents -->



<!-- ``` -->

