
<!-- can't figure out what is wrong with this table  -->
<!-- it is definitely related to collapsing the rows, but it was  -->
<!--  working  completely fine yesterday. I even copied the old code  -->
<!--  and I get the same error  -->

```{r tfc-definition-methods, eval=FALSE}
tfc_definition_methods <- readr::read_csv(
  here::here("data/lit-review-data/tables/selected_transitional_fines_content_studies_one_per_row.csv"),
  col_types = 'ccccc', na = '') %>% 
  tidyr::fill(dplyr::everything()) %>%
  dplyr::mutate(reference = paste0(citation, " (", year, ") "),
                tests_performed = paste('\u00B7', tests_performed)) %>% 
  dplyr::arrange(citation) %>% 
  dplyr::group_by(across(-tests_performed)) %>% 
  dplyr::arrange(tests_performed, .by_group = TRUE) %>% 
  dplyr::ungroup() %>% 
  dplyr::select(reference, fines_type, tests_performed, reported_tfc)
  
# tfc_definition_methods
tfc_study_column_names <- c(
  'Reference',
  'Type of fines',
  'Tests performed',
  'Reported TFC (% by mass)'
)
tfc_def_kable <- tfc_definition_methods %>% 
  kbl(format = 'latex',
      booktabs = TRUE,
      linesep = "",
      align = 'lllc',
      col.names = tfc_study_column_names,
      caption = 'Selected studies on the transitional fines content (TFC) of coarse-fine mixtures. Methods used to identify the TFC depends on the problem of interest.',
      caption.short = 'Relevant studies on transitional fines content (TFC)') %>% 
 kableExtra::collapse_rows(columns = c(1, 2, 4),
                latex_hline = 'major') 
tfc_def_kable
```


try this version from may 23??

```{r tfc-definition-methods-old}

```

